# Generated by Django 3.2.8 on 2022-12-13 13:36

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('article', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to=product.models.image_folder)),
                ('status', models.CharField(choices=[('HV', 'В наличии'), ('OR', 'Под заказ'), ('EX', 'Ожидается поступление'), ('OOS', 'Нет в наличии'), ('NP', 'Не производится')], default='HV', max_length=3, verbose_name='статус')),
            ],
        ),
    ]
